
package volandouyMobile.servidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Publicador", targetNamespace = "http://servidor.volandouy/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Publicador {


    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.RutaArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getRutasDeVueloIngresadasRechazadasAerolineaRequest", output = "http://servidor.volandouy/Publicador/getRutasDeVueloIngresadasRechazadasAerolineaResponse")
    public RutaArrayDto getRutasDeVueloIngresadasRechazadasAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.ComprasPaqueteArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getComprasDePaquetesClienteRequest", output = "http://servidor.volandouy/Publicador/getComprasDePaquetesClienteResponse")
    public ComprasPaqueteArrayDto getComprasDePaquetesCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/noTieneVuelosVigentesRequest", output = "http://servidor.volandouy/Publicador/noTieneVuelosVigentesResponse")
    public boolean noTieneVuelosVigentes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/estaRutaEnAlgunPaqueteRequest", output = "http://servidor.volandouy/Publicador/estaRutaEnAlgunPaqueteResponse")
    public boolean estaRutaEnAlgunPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.RutaArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getRutasDeVueloAceptadasAerolineaRequest", output = "http://servidor.volandouy/Publicador/getRutasDeVueloAceptadasAerolineaResponse")
    public RutaArrayDto getRutasDeVueloAceptadasAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://servidor.volandouy/Publicador/finalizarRutaRequest", output = "http://servidor.volandouy/Publicador/finalizarRutaResponse")
    public void finalizarRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/sigueAUsuarioRequest", output = "http://servidor.volandouy/Publicador/sigueAUsuarioResponse")
    public boolean sigueAUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.ReservasArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getReservasClienteRequest", output = "http://servidor.volandouy/Publicador/getReservasClienteResponse")
    public ReservasArrayDto getReservasCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://servidor.volandouy/Publicador/seguirAUsuarioRequest", output = "http://servidor.volandouy/Publicador/seguirAUsuarioResponse")
    public void seguirAUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/compararFechasRequest", output = "http://servidor.volandouy/Publicador/compararFechasResponse")
    public int compararFechas(
        @WebParam(name = "arg0", partName = "arg0")
        DtFecha arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtFecha arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://servidor.volandouy/Publicador/dejarDeSeguirRequest", output = "http://servidor.volandouy/Publicador/dejarDeSeguirResponse")
    public void dejarDeSeguir(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns volandouy.servidor.ImagenesDto
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getFilesRequest", output = "http://servidor.volandouy/Publicador/getFilesResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://servidor.volandouy/Publicador/getFiles/Fault/IOException")
    })
    public ImagenesDto getFiles()
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns volandouy.servidor.DtFecha
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getFechaActualRequest", output = "http://servidor.volandouy/Publicador/getFechaActualResponse")
    public DtFecha getFechaActual();

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://servidor.volandouy/Publicador/realizarCheckInRequest", output = "http://servidor.volandouy/Publicador/realizarCheckInResponse")
    public void realizarCheckIn(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.volandouy/Publicador/setImagenRequest", output = "http://servidor.volandouy/Publicador/setImagenResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://servidor.volandouy/Publicador/setImagen/Fault/IOException")
    })
    public void setImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        byte[] arg2)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/rutaDeAerolineaRequest", output = "http://servidor.volandouy/Publicador/rutaDeAerolineaResponse")
    public int rutaDeAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns volandouy.servidor.CategoriasArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getCategoriasRequest", output = "http://servidor.volandouy/Publicador/getCategoriasResponse")
    public CategoriasArrayDto getCategorias();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaRutaDeVueloRequest", output = "http://servidor.volandouy/Publicador/altaRutaDeVueloResponse")
    public String altaRutaDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        DtHora arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        DtFecha arg9,
        @WebParam(name = "arg10", partName = "arg10")
        CategoriasArrayDto arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaPaqueteRequest", output = "http://servidor.volandouy/Publicador/altaPaqueteResponse")
    public String altaPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        DtFecha arg4);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaCompraPaqueteRequest", output = "http://servidor.volandouy/Publicador/altaCompraPaqueteResponse")
    public String altaCompraPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DtFecha arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.ClienteDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getClienteRequest", output = "http://servidor.volandouy/Publicador/getClienteResponse")
    public ClienteDto getCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaVueloRequest", output = "http://servidor.volandouy/Publicador/altaVueloResponse")
    public String altaVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        DtFecha arg2,
        @WebParam(name = "arg3", partName = "arg3")
        DtHora arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        DtFecha arg6);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaReservaRequest", output = "http://servidor.volandouy/Publicador/altaReservaResponse")
    public String altaReserva(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        EnumAsiento arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        DtFecha arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        PersonasArrayDto arg7);

    /**
     * 
     * @return
     *     returns volandouy.servidor.PaisArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getPaisesRequest", output = "http://servidor.volandouy/Publicador/getPaisesResponse")
    public PaisArrayDto getPaises();

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.PaisDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getCiudadesPaisRequest", output = "http://servidor.volandouy/Publicador/getCiudadesPaisResponse")
    public PaisDto getCiudadesPais(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.RutaArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getRutasDeVueloRequest", output = "http://servidor.volandouy/Publicador/getRutasDeVueloResponse")
    public RutaArrayDto getRutasDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns volandouy.servidor.RutaArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getAllRutasDeVueloRequest", output = "http://servidor.volandouy/Publicador/getAllRutasDeVueloResponse")
    public RutaArrayDto getAllRutasDeVuelo();

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.VueloDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getVueloRequest", output = "http://servidor.volandouy/Publicador/getVueloResponse")
    public VueloDto getVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.PaqueteDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getPaqueteRequest", output = "http://servidor.volandouy/Publicador/getPaqueteResponse")
    public PaqueteDto getPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.RutaDeVueloDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getRutaDeVueloRequest", output = "http://servidor.volandouy/Publicador/getRutaDeVueloResponse")
    public RutaDeVueloDto getRutaDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns volandouy.servidor.PaqueteArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getPaquetesRequest", output = "http://servidor.volandouy/Publicador/getPaquetesResponse")
    public PaqueteArrayDto getPaquetes();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaClienteRequest", output = "http://servidor.volandouy/Publicador/altaClienteResponse")
    public String altaCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        DtFecha arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        EnumDocumento arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8);

    /**
     * 
     * @return
     *     returns volandouy.servidor.UsuarioArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getUsuariosRequest", output = "http://servidor.volandouy/Publicador/getUsuariosResponse")
    public UsuarioArrayDto getUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.AerolineaDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getAerolineaRequest", output = "http://servidor.volandouy/Publicador/getAerolineaResponse")
    public AerolineaDto getAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.UsuarioDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getUsuarioRequest", output = "http://servidor.volandouy/Publicador/getUsuarioResponse")
    public UsuarioDto getUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns volandouy.servidor.AerolineasArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getAerolineasRequest", output = "http://servidor.volandouy/Publicador/getAerolineasResponse")
    public AerolineasArrayDto getAerolineas();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/modificarClienteRequest", output = "http://servidor.volandouy/Publicador/modificarClienteResponse")
    public String modificarCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        DtFecha arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        EnumDocumento arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns volandouy.servidor.DtFecha
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getFechaRequest", output = "http://servidor.volandouy/Publicador/getFechaResponse")
    public DtFecha getFecha(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/altaAerolineaRequest", output = "http://servidor.volandouy/Publicador/altaAerolineaResponse")
    public String altaAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns volandouy.servidor.DtHora
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getHoraRequest", output = "http://servidor.volandouy/Publicador/getHoraResponse")
    public DtHora getHora(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.PaquetesRutaArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getPaquetesRutaRequest", output = "http://servidor.volandouy/Publicador/getPaquetesRutaResponse")
    public PaquetesRutaArrayDto getPaquetesRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/modificarAerolineaRequest", output = "http://servidor.volandouy/Publicador/modificarAerolineaResponse")
    public String modificarAerolinea(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.ReservasArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getReservasVueloRequest", output = "http://servidor.volandouy/Publicador/getReservasVueloResponse")
    public ReservasArrayDto getReservasVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns volandouy.servidor.VueloArrayDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getVuelosRutaRequest", output = "http://servidor.volandouy/Publicador/getVuelosRutaResponse")
    public VueloArrayDto getVuelosRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.volandouy/Publicador/getCpRestantesRutaRequest", output = "http://servidor.volandouy/Publicador/getCpRestantesRutaResponse")
    public int getCpRestantesRuta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

}
